/* =============================  IB_CONF_COMPONENT 业务模块组件管理表 --- =============================  */
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('20001','special','专车模块','0','sModule');
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('20002','special','表存储设计器','20001','Table');
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('20003','special','表单设计器','20001','Form');
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('20004','special','流程表设计器','20001','BpmTable');
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('20005','special','流程表单设计器','20001','BpmForm');
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('20006','special','流程设计器','20001','Bpm');
/* ================= 菜单管理表  ==================   */
INSERT INTO IB_MENU(ID,MENUNAME,MENULEVEL,MENUURL,MENUIFRAME,MENUORDER,PARENTID) VALUES('specialmOne1','专车模块','1','#','URL','5','0');
delete from IB_MENU where ID='specialmTwo1';
INSERT INTO IB_MENU(ID,MENUNAME,MENULEVEL,MENUURL,MENUIFRAME,MENUORDER,PARENTID) VALUES('specialmTwo1','专车司机信息管理','2','/special_driver_info/special_driver_info-list.do','URL','1','specialmOne1');
delete from IB_MENU where ID='specialmTwo2';
INSERT INTO IB_MENU(ID,MENUNAME,MENULEVEL,MENUURL,MENUIFRAME, MENUORDER,PARENTID) VALUES('specialmTwo2','专车使用车型管理','2','/specialcar_use_type_mgr/specialcar_use_type_mgr-list.do','URL','2','specialmOne1');
delete from IB_MENU where ID='specialmTwo3';
INSERT INTO IB_MENU(ID,MENUNAME,MENULEVEL,MENUURL,MENUIFRAME, MENUORDER,PARENTID) VALUES('specialmTwo3','专车司机报名','2','/special_driver_signup/special_driver_signup-list.do','URL','3','specialmOne1');
delete from IB_MENU where ID='specialmTwo4';
INSERT INTO IB_MENU(ID,MENUNAME,MENULEVEL,MENUURL,MENUIFRAME, MENUORDER,PARENTID) VALUES('specialmTwo4','专车司机记录管理','2','/special_record_mgr/special_record_mgr-list.do','URL','4','specialmOne1');

INSERT INTO IB_MENU_ROLE_DEF(MENU_ID,ROLE_DEF_ID) VALUES('specialmOne1','2');
INSERT INTO IB_MENU_ROLE_DEF(MENU_ID,ROLE_DEF_ID) VALUES('specialmTwo1','2');
INSERT INTO IB_MENU_ROLE_DEF(MENU_ID,ROLE_DEF_ID) VALUES('specialmTwo2','2');
INSERT INTO IB_MENU_ROLE_DEF(MENU_ID,ROLE_DEF_ID) VALUES('specialmTwo3','2');
INSERT INTO IB_MENU_ROLE_DEF(MENU_ID,ROLE_DEF_ID) VALUES('specialmTwo4','2');

/* ======================== 业务模块组件管理表 ====================  */
/* ================================================================================   */
/* ================================  专车司机信息管理表    =================================   */
/* ================================================================================   */
/* ====== 专车司机信息管理 =====  */
/*======= 创建表 ==========*/
DROP TABLE IF EXISTS IB_SPECIAL_DRIVER_INFO;
CREATE TABLE IB_SPECIAL_DRIVER_INFO (ACCOUNT VARCHAR(16), NAME VARCHAR(8), CELLPHONE VARCHAR(16), EID VARCHAR(18), SEX VARCHAR(8), ADDRESS VARCHAR(128), PUBLIAHGRD VARCHAR(32), BIRTH DATETIME, NATION VARCHAR(16), EIDURL VARCHAR(128), DRIVERNUM VARCHAR(32), DRIVERFILENUM VARCHAR(32), PREDRIVERDATE DATETIME, PRECARTYPE VARCHAR(8), VALIDSTARTDATE DATETIME, VALIDTREM VARCHAR(8), DRIVERNUMURL VARCHAR(128), CARNAME VARCHAR(32), CARNUM VARCHAR(16), CARFRAMENUM VARCHAR(32), CARCOLOR VARCHAR(16), DRIVERTYPE VARCHAR(16), CONTRACTID VARCHAR(32), CONTRACTTERM VARCHAR(16), CONTRACTSUMDEPOSIT VARCHAR(16), CONTRACTVALIDDAY DATETIME, CONTRACTOVERDATE DATETIME, PERMONTHRENT VARCHAR(8), PERMONTHDAY VARCHAR(8), CARDEPOSIT VARCHAR(18), CONTRACTCOPYUPLOAD VARCHAR(128), STATUS VARCHAR(8), PLATFORMTO VARCHAR(32), LOGINTEL VARCHAR(18), TOSOURCE VARCHAR(32), RECOMMENDED VARCHAR(16), BUSIPEOPLE VARCHAR(16), SALESMAN VARCHAR(16), REMARKS VARCHAR(256), COMPANYBANKACT VARCHAR(24), COMPANYBANK VARCHAR(24), PAYROLLBANKACT VARCHAR(24), PAYROLLBANK VARCHAR(24), UDNUMBER VARCHAR(16), UDUSERNAME VARCHAR(16), UBERNAME VARCHAR(16), UBERPASSWORD VARCHAR(16), UBERONLINE VARCHAR(8), DDONLINE VARCHAR(4), WAGEPLAN VARCHAR(32), TTCARD VARCHAR(16), BYDCARD VARCHAR(16), PTDKCARD VARCHAR(16), SBCARD VARCHAR(16), ID VARCHAR(64), SCOPEID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
/* ====== 插入数据 =====  */
insert into ib_special_driver_info(ACCOUNT,NAME,CELLPHONE,EID,SEX,ADDRESS,PUBLIAHGRD,BIRTH,NATION,EIDURL,DRIVERNUM,DRIVERFILENUM,PREDRIVERDATE,PRECARTYPE,VALIDSTARTDATE,VALIDTREM,DRIVERNUMURL,CARNAME,CARNUM,CARFRAMENUM,CARCOLOR,DRIVERTYPE,CONTRACTID,CONTRACTTERM,CONTRACTSUMDEPOSIT,CONTRACTVALIDDAY,CONTRACTOVERDATE,PERMONTHRENT,PERMONTHDAY,CARDEPOSIT,CONTRACTCOPYUPLOAD,STATUS,ID,SCOPEID) values ('A5236','刘锦','13636536654','230102199909090019','男','北京市朝阳区','交通局','2015-12-02 00:00:00','汉','','230103195508242212','230101542011',NULL,'C',NULL,'','','天籁2.0基本型2015版','京A123456','','','自营司机','B050','12','20000','2015-12-09 00:00:00','2015-12-02 00:00:00','4500','1','15000','','正常','a5893721-262f-4c31-9bbd-1c5b57d44f71',NULL),('A5237','王大民','13452636521','230102199909090019','男','北京朝阳区','交通局','2015-12-17 00:00:00','汉','','230103195508242212','230101542011',NULL,'A',NULL,'2','','丰田凯美瑞2.0G','京A123456','3','','租车司机','B049','3','20000','2015-12-16 00:00:00','2015-12-01 00:00:00','4500','3','20000','','已解约','f4a89e1f-d5ff-4564-a553-acff71def1e8',NULL);
/*======= 表单 ==========*/
 delete from ib_conf_form where FORMNAME='specialdriverinfo';
 insert into ib_conf_form(ID,PACKAGENAME,FORMNAME,FORMTITLE,FORMURL, ISEDIT,ISADD,ISDELETE,ISQUERY,ISEXCELEXPORT,ISIMPORTEXPORT,ISBPMFORM) values ('aacc3eeb-43d9-4980-b2ce-985221cdbf3a','special','specialdriverinfo','专车司机信息','/special_driver_info/special_driver_info-list.do',1,1,1,1,1,2,2);
/*======= 表单对应表 ==========*/
 delete from ib_conf_form_table where FORMNAME='specialdriverinfo';
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO','main');
/*======= 表单字段 ==========*/
 delete from ib_conf_form_table_colums where FORMNAME='specialdriverinfo';
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.ACCOUNT','账号','ACCOUNT','IB_SPECIAL_DRIVER_INFO',1,'10','','','1','1','2','1','','{"jsplist":[{"inputKey":"account","inputValue":"customercell","inputTitle":"客户姓名"},{"inputKey":"name","inputValue":"customername","inputTitle":"客户电话"},{"inputKey":"cellphone","inputValue":"customercell","inputTitle":"客户姓名"}],"className":"IB_CUSTOMER_MGR","queryTitle":"客户姓名","queryName":"customername"}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.NAME','司机姓名','NAME','IB_SPECIAL_DRIVER_INFO',2,'1','','','1','1','1','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.SBCARD','社保','SBCARD','IB_SPECIAL_DRIVER_INFO',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.TTCARD','通途电卡卡号','TTCARD','IB_SPECIAL_DRIVER_INFO',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.BYDCARD','BYD电卡编号','BYDCARD','IB_SPECIAL_DRIVER_INFO',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.DDONLINE','滴滴出行上线状态','DDONLINE','IB_SPECIAL_DRIVER_INFO',2,'6','','','1','1','2','1','','[{"key":"是","value":"是"},{"key":"否","value":"否"}]');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.LOGINTEL','登录手机号','LOGINTEL','IB_SPECIAL_DRIVER_INFO',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.PTDKCARD','普天电卡卡号','PTDKCARD','IB_SPECIAL_DRIVER_INFO',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.UBERNAME','Ubername','UBERNAME','IB_SPECIAL_DRIVER_INFO',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.UDNUMBER','U盾号码','UDNUMBER','IB_SPECIAL_DRIVER_INFO',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.WAGEPLAN','工资(合作/合同)方案','WAGEPLAN','IB_SPECIAL_DRIVER_INFO',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.UBERONLINE','Uber上线状态','UBERONLINE','IB_SPECIAL_DRIVER_INFO',2,'6','','','1','1','2','1','','[{"key":"是","value":"是"},{"key":"否","value":"否"}]');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.UDUSERNAME','U盾用户名','UDUSERNAME','IB_SPECIAL_DRIVER_INFO',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.COMPANYBANK','公司银行开户行','COMPANYBANK','IB_SPECIAL_DRIVER_INFO',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.PAYROLLBANK','工资卡开户行','PAYROLLBANK','IB_SPECIAL_DRIVER_INFO',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.UBERPASSWORD','Uberpassword','UBERPASSWORD','IB_SPECIAL_DRIVER_INFO',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.COMPANYBANKACT','公司银行账号','COMPANYBANKACT','IB_SPECIAL_DRIVER_INFO',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.PAYROLLBANKACT','工资卡银行账号','PAYROLLBANKACT','IB_SPECIAL_DRIVER_INFO',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.CELLPHONE','司机电话','CELLPHONE','IB_SPECIAL_DRIVER_INFO',3,'1','','','1','1','1','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.EID','司机身份证号码','EID','IB_SPECIAL_DRIVER_INFO',4,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.SEX','性别','SEX','IB_SPECIAL_DRIVER_INFO',5,'6','','','1','1','2','1','','[{"key":"男","value":"男"},{"key":"女","value":"女"}]');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.ADDRESS','地址','ADDRESS','IB_SPECIAL_DRIVER_INFO',6,'2','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.PUBLIAHGRD','发证机关','PUBLIAHGRD','IB_SPECIAL_DRIVER_INFO',7,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.BIRTH','出生日期','BIRTH','IB_SPECIAL_DRIVER_INFO',8,'3','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.NATION','民族','NATION','IB_SPECIAL_DRIVER_INFO',9,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.EIDURL','身份证附件','EIDURL','IB_SPECIAL_DRIVER_INFO',10,'11','','','1','1','2','2','','{"pathName":"ibfile"}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.DRIVERNUM','司机驾驶证编号','DRIVERNUM','IB_SPECIAL_DRIVER_INFO',11,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.DRIVERFILENUM','司机驾驶证档案号','DRIVERFILENUM','IB_SPECIAL_DRIVER_INFO',12,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.PREDRIVERDATE','驾照初领日期','PREDRIVERDATE','IB_SPECIAL_DRIVER_INFO',13,'3','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.PRECARTYPE','驾照类别','PRECARTYPE','IB_SPECIAL_DRIVER_INFO',14,'6','','','1','1','1','1','','[{"key":"A","value":"A"},{"key":"B","value":"B"},{"key":"C","value":"C"},{"key":"E","value":"E"}]');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.VALIDSTARTDATE','有效起始日期','VALIDSTARTDATE','IB_SPECIAL_DRIVER_INFO',15,'3','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.VALIDTREM','有效期限','VALIDTREM','IB_SPECIAL_DRIVER_INFO',16,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.DRIVERNUMURL','驾驶证扫描附件','DRIVERNUMURL','IB_SPECIAL_DRIVER_INFO',17,'11','','','1','1','2','2','','{"pathName":"ibfile"}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.CARNAME','车型名称','CARNAME','IB_SPECIAL_DRIVER_INFO',20,'10','','','1','1','2','1','','{"jsplist":[{"inputKey":"carname","inputValue":"typename","inputTitle":"型号名称"},{"inputKey":"carnum","inputValue":"carnum","inputTitle":"车牌号"},{"inputKey":"carframenum","inputValue":"carframenum","inputTitle":"车架号"},{"inputKey":"carcolor","inputValue":"carcolor","inputTitle":"车辆颜色"}],"className":"IB_CAR_MGR","queryTitle":"型号名称","queryName":"typename"}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.CARNUM','车牌号码','CARNUM','IB_SPECIAL_DRIVER_INFO',21,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.CARFRAMENUM','车架号','CARFRAMENUM','IB_SPECIAL_DRIVER_INFO',22,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.CARCOLOR','颜色','CARCOLOR','IB_SPECIAL_DRIVER_INFO',23,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.DRIVERTYPE','司机签约类型','DRIVERTYPE','IB_SPECIAL_DRIVER_INFO',30,'6','','','1','1','2','1','','[{"key":"自营司机","value":"自营司机"},{"key":"租车司机","value":"租车司机"},{"key":"以租代购","value":"以租代购"}]');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.CONTRACTID','合同编号','CONTRACTID','IB_SPECIAL_DRIVER_INFO',31,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.CONTRACTTERM','合同期限','CONTRACTTERM','IB_SPECIAL_DRIVER_INFO',32,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.CONTRACTSUMDEPOSIT','合同总押金','CONTRACTSUMDEPOSIT','IB_SPECIAL_DRIVER_INFO',33,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.CONTRACTVALIDDAY','合同生效日','CONTRACTVALIDDAY','IB_SPECIAL_DRIVER_INFO',34,'3','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.CONTRACTOVERDATE','合同终止日期','CONTRACTOVERDATE','IB_SPECIAL_DRIVER_INFO',35,'3','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.PERMONTHRENT','签订租金','PERMONTHRENT','IB_SPECIAL_DRIVER_INFO',36,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.PERMONTHDAY','每月交租日','PERMONTHDAY','IB_SPECIAL_DRIVER_INFO',37,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.CARDEPOSIT','车辆押金','CARDEPOSIT','IB_SPECIAL_DRIVER_INFO',38,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.CONTRACTCOPYUPLOAD','合同扫描件上传','CONTRACTCOPYUPLOAD','IB_SPECIAL_DRIVER_INFO',39,'11','','','1','1','2','2','','{"pathName":"ibfile"}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.STATUS','状态','STATUS','IB_SPECIAL_DRIVER_INFO',40,'6','','','1','1','2','1','','[{"key":"正常","value":"正常"},{"key":"已解约","value":"已解约"}]');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.PLATFORMTO','加入平台','PLATFORMTO','IB_SPECIAL_DRIVER_INFO',41,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.TOSOURCE','来源','TOSOURCE','IB_SPECIAL_DRIVER_INFO',43,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.SALESMAN','业务员','SALESMAN','IB_SPECIAL_DRIVER_INFO',44,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.BUSIPEOPLE','洽谈人','BUSIPEOPLE','IB_SPECIAL_DRIVER_INFO',45,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.RECOMMENDED','推荐人','RECOMMENDED','IB_SPECIAL_DRIVER_INFO',46,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriverinfo','IB_SPECIAL_DRIVER_INFO.REMARKS','备注','REMARKS','IB_SPECIAL_DRIVER_INFO',47,'2','','','1','1','2','1','','');
/*======= 表 ==========*/
 delete from ib_conf_table where TABLENAME='IB_SPECIAL_DRIVER_INFO';
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('017bb121-9ebd-4d73-808b-1bddacf3365a','special','IB_SPECIAL_DRIVER_INFO','专车司机信息','1','null',2);
/*======= 表字段 ==========*/
 delete from ib_conf_table_columns where TABLENAME='IB_SPECIAL_DRIVER_INFO';
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','ACCOUNT','账号','VARCHAR','16','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','NAME','司机姓名','VARCHAR','8','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','CELLPHONE','司机电话','VARCHAR','16','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','EID','司机身份证号码','VARCHAR','18','是','',4);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','SEX','性别','VARCHAR','8','是','',5);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','ADDRESS','地址','VARCHAR','128','是','',6);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','PUBLIAHGRD','发证机关','VARCHAR','32','是','',7);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','BIRTH','出生日期','DATE','0','是','',8);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','NATION','民族','VARCHAR','16','是','',9);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','EIDURL','身份证附件','VARCHAR','128','是','',10);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','DRIVERNUM','司机驾驶证编号','VARCHAR','32','是','',11);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','DRIVERFILENUM','司机驾驶证档案号','VARCHAR','32','是','',12);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','PREDRIVERDATE','驾照初领日期','DATE','0','是','',13);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','PRECARTYPE','驾照类别','VARCHAR','8','是','',14);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','VALIDSTARTDATE','有效起始日期','DATE','0','是','',15);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','VALIDTREM','有效期限','VARCHAR','8','是','',16);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','DRIVERNUMURL','驾驶证扫描附件','VARCHAR','128','是','',17);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','CARNAME','车型名称','VARCHAR','32','是','',20);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','CARNUM','车牌号码','VARCHAR','16','是','',21);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','CARFRAMENUM','车架号','VARCHAR','32','是','',22);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','CARCOLOR','颜色','VARCHAR','16','是','',23);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','DRIVERTYPE','司机签约类型','VARCHAR','16','是','',30);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','CONTRACTID','合同编号','VARCHAR','32','是','',31);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','CONTRACTTERM','合同期限','VARCHAR','16','是','',32);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','CONTRACTSUMDEPOSIT','合同总押金','VARCHAR','16','是','',33);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','CONTRACTVALIDDAY','合同生效日','DATE','0','是','',34);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','CONTRACTOVERDATE','合同终止日期','DATE','0','是','',35);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','PERMONTHRENT','签订租金','VARCHAR','8','是','',36);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','PERMONTHDAY','每月交租日','VARCHAR','8','是','',37);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','CARDEPOSIT','车辆押金','VARCHAR','18','是','',38);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','CONTRACTCOPYUPLOAD','合同扫描件上传','VARCHAR','128','是','',39);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','STATUS','状态','VARCHAR','8','是','',40);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','PLATFORMTO','加入平台','VARCHAR','32','是','',41);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','LOGINTEL','登录手机号','VARCHAR','18','是','',42);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','TOSOURCE','来源','VARCHAR','32','是','',43);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','RECOMMENDED','推荐人','VARCHAR','16','是','',44);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','BUSIPEOPLE','洽谈人','VARCHAR','16','是','',45);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','SALESMAN','业务员','VARCHAR','16','是','',46);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','REMARKS','备注','VARCHAR','256','是','',47);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','COMPANYBANKACT','公司银行账号','VARCHAR','24','是','',48);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','COMPANYBANK','公司银行开户行','VARCHAR','24','是','',49);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','PAYROLLBANKACT','工资卡银行账号','VARCHAR','24','是','',50);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','PAYROLLBANK','工资卡开户行','VARCHAR','24','是','',51);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','UDNUMBER','U盾号码','VARCHAR','16','是','',52);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','UDUSERNAME','U盾用户名','VARCHAR','16','是','',53);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','UBERNAME','Ubername','VARCHAR','16','是','',54);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','UBERPASSWORD','Uberpassword','VARCHAR','16','是','',55);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','UBERONLINE','Uber上线状态','VARCHAR','8','是','',56);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','DDONLINE','滴滴出行上线状态','VARCHAR','4','是','',57);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','WAGEPLAN','工资(合作/合同)方案','VARCHAR','32','是','',58);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','TTCARD','通途电卡卡号','VARCHAR','16','是','',59);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','BYDCARD','BYD电卡编号','VARCHAR','16','是','',60);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','PTDKCARD','普天电卡卡号','VARCHAR','16','是','',61);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','SBCARD','社保','VARCHAR','16','是','',62);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_INFO','SCOPEID','范围','VARCHAR','64','否','',92);



/* ====== 专车使用车型管理 =====  */
DROP TABLE IF EXISTS IB_SPECIALCAR_USE_TYPE_MGR;
CREATE TABLE IB_SPECIALCAR_USE_TYPE_MGR (CARTYPE VARCHAR(32), NEWOROLD VARCHAR(16), CONTRFORTHREEMTH VARCHAR(16), CONTRFORSIXMTH VARCHAR(16), CONTRFORSONEYEAR VARCHAR(16), CONTRFORSTWOYEAR VARCHAR(16), CARDEPOSIT VARCHAR(16), ILLEGALDEPOSIT VARCHAR(16), STATUS VARCHAR(8), PLAT VARCHAR(64), ID VARCHAR(64), SCOPEID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
/* ====== 插入数据 =====  */
insert into ib_specialcar_use_type_mgr(CARTYPE,NEWOROLD,CONTRFORTHREEMTH,CONTRFORSIXMTH,CONTRFORSONEYEAR,CONTRFORSTWOYEAR,CARDEPOSIT,ILLEGALDEPOSIT,STATUS,ID,SCOPEID) values ('丰田凯美瑞2.0G','旧车','4300','4200','4100','4000','15000','5000','Off','8402c731-d3d7-4c04-a749-01b1616f0ca8',NULL),('天籁2.0基本型2015版','全新','4500','4400','4300','4200','15000','5000','On','df3e42d5-c509-4520-ab70-7fca957eb60a',NULL);
/* ================================================================================   */
/* ================================  专车使用车型管理    =================================   */
/* ================================================================================   */
/*======= 表单 ==========*/
delete from ib_conf_form where FORMNAME='specialcarusetypemgr';
insert into ib_conf_form(ID,PACKAGENAME,FORMNAME,FORMTITLE,FORMURL, ISEDIT,ISADD,ISDELETE,ISQUERY,ISEXCELEXPORT,ISIMPORTEXPORT,ISBPMFORM) values ('d43035a3-7713-49b7-a808-8058e95b4724','special','specialcarusetypemgr','专车使用车型管理','/specialcar_use_type_mgr/specialcar_use_type_mgr-list.do',1,1,1,1,1,2,2);
/*======= 表单对应表 ==========*/
delete from ib_conf_form_table where FORMNAME='specialcarusetypemgr';
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('special','specialcarusetypemgr','IB_SPECIALCAR_USE_TYPE_MGR','main');
/*======= 表单字段 ==========*/
delete from ib_conf_form_table_colums where FORMNAME='specialcarusetypemgr';
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialcarusetypemgr','IB_SPECIALCAR_USE_TYPE_MGR.CARTYPE','车型名称','CARTYPE','IB_SPECIALCAR_USE_TYPE_MGR',1,'7','','','1','1','1','1','','{"sql":"select typename vKey, typename vValue from IB_CAR_TYPE_INFO "}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialcarusetypemgr','IB_SPECIALCAR_USE_TYPE_MGR.NEWOROLD','新旧程度','NEWOROLD','IB_SPECIALCAR_USE_TYPE_MGR',2,'6','','','1','1','2','1','','[{"key":"全新","value":"全新"},{"key":"旧车","value":"旧车"}]');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialcarusetypemgr','IB_SPECIALCAR_USE_TYPE_MGR.CONTRFORTHREEMTH','3个月合同每月租金','CONTRFORTHREEMTH','IB_SPECIALCAR_USE_TYPE_MGR',3,'5','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialcarusetypemgr','IB_SPECIALCAR_USE_TYPE_MGR.CONTRFORSIXMTH','6个月合同月租金','CONTRFORSIXMTH','IB_SPECIALCAR_USE_TYPE_MGR',4,'5','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialcarusetypemgr','IB_SPECIALCAR_USE_TYPE_MGR.CONTRFORSONEYEAR','1年合同每月租金','CONTRFORSONEYEAR','IB_SPECIALCAR_USE_TYPE_MGR',5,'5','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialcarusetypemgr','IB_SPECIALCAR_USE_TYPE_MGR.CONTRFORSTWOYEAR','2年合同月租金','CONTRFORSTWOYEAR','IB_SPECIALCAR_USE_TYPE_MGR',6,'5','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialcarusetypemgr','IB_SPECIALCAR_USE_TYPE_MGR.CARDEPOSIT','车辆押金','CARDEPOSIT','IB_SPECIALCAR_USE_TYPE_MGR',7,'5','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialcarusetypemgr','IB_SPECIALCAR_USE_TYPE_MGR.ILLEGALDEPOSIT','违章押金','ILLEGALDEPOSIT','IB_SPECIALCAR_USE_TYPE_MGR',8,'5','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialcarusetypemgr','IB_SPECIALCAR_USE_TYPE_MGR.STATUS','状态','STATUS','IB_SPECIALCAR_USE_TYPE_MGR',9,'6','','','1','1','2','1','','[{"key":"On","value":"On"},{"key":"Off","value":"Off"}]');
/*======= 表 ==========*/
 delete from ib_conf_table where TABLENAME='IB_SPECIALCAR_USE_TYPE_MGR';
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('7cc126e2-c7f8-49d3-9d6d-84aa6d7870c3','special','IB_SPECIALCAR_USE_TYPE_MGR','专车使用车型管理','1','null',2);
/*======= 表字段 ==========*/
 delete from ib_conf_table_columns where TABLENAME='IB_SPECIALCAR_USE_TYPE_MGR';
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIALCAR_USE_TYPE_MGR','CARTYPE','车型名称','VARCHAR','16','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIALCAR_USE_TYPE_MGR','NEWOROLD','新旧程度','VARCHAR','16','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIALCAR_USE_TYPE_MGR','CONTRFORTHREEMTH','3个月合同每月租金','VARCHAR','16','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIALCAR_USE_TYPE_MGR','CONTRFORSIXMTH','6个月合同月租金','VARCHAR','16','是','',4);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIALCAR_USE_TYPE_MGR','CONTRFORSONEYEAR','1年合同月租金租金','VARCHAR','16','是','',5);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIALCAR_USE_TYPE_MGR','CONTRFORSTWOYEAR','2年合同月租金','VARCHAR','16','是','',6);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIALCAR_USE_TYPE_MGR','CARDEPOSIT','汽车押金','VARCHAR','16','是','',7);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIALCAR_USE_TYPE_MGR','ILLEGALDEPOSIT','违章押金','VARCHAR','16','是','',8);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIALCAR_USE_TYPE_MGR','STATUS','状态','VARCHAR','8','是','',9);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIALCAR_USE_TYPE_MGR','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIALCAR_USE_TYPE_MGR','SCOPEID','范围','VARCHAR','64','否','',92);

/* ====== 专车司机报名 =====  */
DROP TABLE IF EXISTS IB_SPECIAL_DRIVER_SIGNUP;
CREATE TABLE IB_SPECIAL_DRIVER_SIGNUP (NAME VARCHAR(8), CELL VARCHAR(16), SUBMITDATE DATETIME, ORDERTYPE VARCHAR(16), CARTYPE VARCHAR(16), SELFCARUSEYEAR VARCHAR(8), CARPHOTE VARCHAR(128), PLATFORMTO VARCHAR(32), PRECONTRACTDATE VARCHAR(16), PREREGISTERDATE DATETIME, PREREGISTERTIME VARCHAR(16), DEALPERSON VARCHAR(8), DEALTIME DATETIME, DEALRESULT VARCHAR(32), PAYRENTMONTH VARCHAR(18), LOGINTEL VARCHAR(18), INPUTTYPE VARCHAR(8), ID VARCHAR(64), SCOPEID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
/* ====== 插入数据 =====  */
insert into ib_special_driver_signup(NAME,CELL,SUBMITDATE,ORDERTYPE,CARTYPE,SELFCARUSEYEAR,CARPHOTE,PLATFORMTO,PRECONTRACTDATE,PREREGISTERDATE,PREREGISTERTIME,DEALPERSON,DEALTIME,DEALRESULT,ID,SCOPEID) values ('刘锦','18956325486','2015-10-26 00:00:00','租车进平台','丰田凯美瑞2.0G','','','滴滴、优步','3个月','2015-11-30 00:00:00','上午','张颜','2015-12-01 00:00:00','已经电话预约','0b70f35a-d53b-41b8-8a6f-8782e3f35a5d',NULL),('陈金泉','13653696345','2015-10-10 00:00:00','自带车','天籁2.0基本型2015版','3','','滴滴、优步','3个月','2015-11-30 00:00:00','上午','未处理','2015-12-01 00:00:00','','a4ba5301-4876-4dfd-8bef-f0a139393ec1',NULL);
/* ================================================================================   */
/* ================================  专车司机报名表    =================================   */
/* ================================================================================   */
/*======= 表单 ==========*/
delete from ib_conf_form where FORMNAME='specialdriversignup';
insert into ib_conf_form(ID,PACKAGENAME,FORMNAME,FORMTITLE,FORMURL, ISEDIT,ISADD,ISDELETE,ISQUERY,ISEXCELEXPORT,ISIMPORTEXPORT,ISBPMFORM) values ('fbdf9d16-0814-4deb-b2c8-6f4552a866bc','special','specialdriversignup','专车司机报名','/special_driver_signup/special_driver_signup-list.do',1,1,1,1,1,2,2);
/*======= 表单对应表 ==========*/
delete from ib_conf_form_table where FORMNAME='specialdriversignup';
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP','main');
/*======= 表单字段 ==========*/
delete from ib_conf_form_table_colums where FORMNAME='specialdriversignup';
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.NAME','姓名','NAME','IB_SPECIAL_DRIVER_SIGNUP',1,'1','','','1','1','1','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.CELL','电话','CELL','IB_SPECIAL_DRIVER_SIGNUP',2,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.INPUTTYPE','入口数据类型','INPUTTYPE','IB_SPECIAL_DRIVER_SIGNUP',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.PAYRENTMONTH','每月租金','PAYRENTMONTH','IB_SPECIAL_DRIVER_SIGNUP',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.SUBMITDATE','提交日期','SUBMITDATE','IB_SPECIAL_DRIVER_SIGNUP',3,'3','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.ORDERTYPE','预约类型','ORDERTYPE','IB_SPECIAL_DRIVER_SIGNUP',4,'6','','','1','1','2','1','','[{"key":"自带车","value":"自带车"},{"key":"租车进平台","value":"租车进平台"}]');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.CARTYPE','车辆型号','CARTYPE','IB_SPECIAL_DRIVER_SIGNUP',5,'7','','','1','1','2','1','','{"sql":"select typename vKey, typename vValue from IB_CAR_TYPE_INFO "}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.SELFCARUSEYEAR','自有车已使用年限','SELFCARUSEYEAR','IB_SPECIAL_DRIVER_SIGNUP',6,'1','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.CARPHOTE','车辆图片','CARPHOTE','IB_SPECIAL_DRIVER_SIGNUP',7,'13','','','1','1','2','2','','{"pathName":"ibimg"}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.PLATFORMTO','想加入的平台','PLATFORMTO','IB_SPECIAL_DRIVER_SIGNUP',8,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.PRECONTRACTDATE','欲签合同期','PRECONTRACTDATE','IB_SPECIAL_DRIVER_SIGNUP',9,'1','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.PREREGISTERDATE','期望注册日期','PREREGISTERDATE','IB_SPECIAL_DRIVER_SIGNUP',10,'3','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.PREREGISTERTIME','期望注册的时间','PREREGISTERTIME','IB_SPECIAL_DRIVER_SIGNUP',11,'6','','','1','1','2','1','','[{"key":"上午","value":"上午"},{"key":"下午","value":"下午"}]');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.DEALPERSON','处理人','DEALPERSON','IB_SPECIAL_DRIVER_SIGNUP',12,'1','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.DEALTIME','处理时间','DEALTIME','IB_SPECIAL_DRIVER_SIGNUP',13,'3','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.DEALRESULT','处理结果','DEALRESULT','IB_SPECIAL_DRIVER_SIGNUP',14,'1','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialdriversignup','IB_SPECIAL_DRIVER_SIGNUP.LOGINTEL','当前登录手机号','LOGINTEL','IB_SPECIAL_DRIVER_SIGNUP',18,'6','','','1','1','2','2','','[{"key":"移动端","value":"移动端"},{"key":"PC端","value":"PC端"}]');
/*======= 表 ==========*/
 delete from ib_conf_table where TABLENAME='IB_SPECIAL_DRIVER_SIGNUP';
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('c604c228-ad71-4549-aad9-9415dca11c97','special','IB_SPECIAL_DRIVER_SIGNUP','专车司机报名','1','null',2);
/*======= 表字段 ==========*/
 delete from ib_conf_table_columns where TABLENAME='IB_SPECIAL_DRIVER_SIGNUP';
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','NAME','姓名','VARCHAR','8','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','CELL','电话','VARCHAR','16','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','SUBMITDATE','提交日期','DATE','0','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','ORDERTYPE','预约类型','VARCHAR','16','是','',4);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','CARTYPE','车辆型号','VARCHAR','16','是','',5);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','SELFCARUSEYEAR','自有车已使用年限','VARCHAR','8','是','',6);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','CARPHOTE','车辆图片','VARCHAR','128','是','',7);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','PLATFORMTO','想加入的平台','VARCHAR','32','是','',8);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','PRECONTRACTDATE','欲签合同期','VARCHAR','16','是','',9);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','PREREGISTERDATE','期望注册日期','DATE','0','是','',10);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','PREREGISTERTIME','期望注册的时间','VARCHAR','16','是','',11);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','DEALPERSON','处理人','VARCHAR','8','是','',12);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','DEALTIME','处理时间','DATE','0','是','',13);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','DEALRESULT','处理结果','VARCHAR','32','是','',14);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','PAYRENTMONTH','每月租金','VARCHAR','18','是','',15);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','LOGINTEL','当前登录手机号','VARCHAR','18','是','',16);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','INPUTTYPE','入口数据类型','VARCHAR','8','是','',17);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_DRIVER_SIGNUP','SCOPEID','范围','VARCHAR','64','否','',92);

/* ====== 专车司机记录管理表 =====  */
DROP TABLE IF EXISTS IB_SPECIAL_RECORD_MGR;
CREATE TABLE IB_SPECIAL_RECORD_MGR (EVENTDATE DATETIME, SENTPERSON VARCHAR(16), INFOTYPE VARCHAR(16), CELLPHONE VARCHAR(16), DRIVERNAME VARCHAR(16), CONTENT VARCHAR(256), ACCOUNT VARCHAR(18), DEALPERSON VARCHAR(16), DEALCONTENT VARCHAR(128), MONTHDATE VARCHAR(8), SENDFLAG VARCHAR(8), ISREADED VARCHAR(8), ID VARCHAR(64), SCOPEID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
/* ================================================================================   */
/* ================================  专车司机记录管理表    =================================   */
/* ================================================================================   */
/*======= 表单 ==========*/
delete from ib_conf_form where FORMNAME='specialrecordmgr';
insert into ib_conf_form(ID,PACKAGENAME,FORMNAME,FORMTITLE,FORMURL, ISEDIT,ISADD,ISDELETE,ISQUERY,ISEXCELEXPORT,ISIMPORTEXPORT,ISBPMFORM) values ('fc8a2982-55fe-498e-bfb4-c4dad7287e41','special','specialrecordmgr','专车司机记录管理','/special_record_mgr/special_record_mgr-list.do',1,1,1,1,1,2,2);
/*======= 表单对应表 ==========*/
delete from ib_conf_form_table where FORMNAME='specialrecordmgr';
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('special','specialrecordmgr','IB_SPECIAL_RECORD_MGR','main');
/*======= 表单字段 ==========*/
 delete from ib_conf_form_table_colums where FORMNAME='specialrecordmgr';
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialrecordmgr','IB_SPECIAL_RECORD_MGR.EVENTDATE','日期','EVENTDATE','IB_SPECIAL_RECORD_MGR',1,'3','','','1','2','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialrecordmgr','IB_SPECIAL_RECORD_MGR.MONTHDATE','年月','MONTHDATE','IB_SPECIAL_RECORD_MGR',2,'14','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialrecordmgr','IB_SPECIAL_RECORD_MGR.SENTPERSON','发送方','SENTPERSON','IB_SPECIAL_RECORD_MGR',2,'6','','','1','1','2','1','','[{"key":"司机","value":"司机"},{"key":"后台记录","value":"后台记录"},{"key":"后台发送","value":"后台发送"}]');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialrecordmgr','IB_SPECIAL_RECORD_MGR.INFOTYPE','信息类别','INFOTYPE','IB_SPECIAL_RECORD_MGR',3,'6','','','1','1','2','1','','[{"key":"司机反馈","value":"司机反馈"},{"key":"后台记录","value":"后台记录"},{"key":"一般通知","value":"一般通知"},{"key":"交租金","value":"交租金"},{"key":"催交押金","value":"催交押金"},{"key":"催交租金","value":"催交租金"},{"key":"其他付款","value":"其他付款"}]');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialrecordmgr','IB_SPECIAL_RECORD_MGR.CELLPHONE','司机电话','CELLPHONE','IB_SPECIAL_RECORD_MGR',4,'1','','','1','1','1','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialrecordmgr','IB_SPECIAL_RECORD_MGR.DRIVERNAME','司机姓名','DRIVERNAME','IB_SPECIAL_RECORD_MGR',5,'10','','','1','1','1','1','','{"jsplist":[{"inputKey":"drivername","inputValue":"customername","inputTitle":"客户姓名"},{"inputKey":"cellphone","inputValue":"customercell","inputTitle":"客户电话"}],"className":"IB_CUSTOMER_MGR","queryTitle":"客户电话","queryName":"customercell"}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialrecordmgr','IB_SPECIAL_RECORD_MGR.CONTENT','内容','CONTENT','IB_SPECIAL_RECORD_MGR',6,'2','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialrecordmgr','IB_SPECIAL_RECORD_MGR.ACCOUNT','金额','ACCOUNT','IB_SPECIAL_RECORD_MGR',7,'5','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialrecordmgr','IB_SPECIAL_RECORD_MGR.DEALPERSON','处理人','DEALPERSON','IB_SPECIAL_RECORD_MGR',8,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialrecordmgr','IB_SPECIAL_RECORD_MGR.DEALCONTENT','处理内容','DEALCONTENT','IB_SPECIAL_RECORD_MGR',9,'2','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialrecordmgr','IB_SPECIAL_RECORD_MGR.SENDFLAG','发送标识','SENDFLAG','IB_SPECIAL_RECORD_MGR',12,'1','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('special','specialrecordmgr','IB_SPECIAL_RECORD_MGR.ISREADED','是否已读','ISREADED','IB_SPECIAL_RECORD_MGR',13,'6','','','1','1','2','2','','[{"key":"是","value":"是"},{"key":"否","value":"否"}]');
/*======= 表 ==========*/
 delete from ib_conf_table where TABLENAME='IB_SPECIAL_RECORD_MGR';
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('c0f83cac-6927-4aea-8f43-0232a4726400','special','IB_SPECIAL_RECORD_MGR','专车司机记录管理','1','null',2);
/*======= 表字段 ==========*/
 delete from ib_conf_table_columns where TABLENAME='IB_SPECIAL_RECORD_MGR';
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_RECORD_MGR','EVENTDATE','日期','DATE','0','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_RECORD_MGR','SENTPERSON','发送方','VARCHAR','16','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_RECORD_MGR','INFOTYPE','信息类别','VARCHAR','16','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_RECORD_MGR','CELLPHONE','司机电话','VARCHAR','16','是','',4);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_RECORD_MGR','DRIVERNAME','司机姓名','VARCHAR','16','是','',5);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_RECORD_MGR','CONTENT','内容','VARCHAR','256','是','',6);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_RECORD_MGR','ACCOUNT','金额','VARCHAR','18','是','',7);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_RECORD_MGR','DEALPERSON','处理人','VARCHAR','16','是','',8);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_RECORD_MGR','DEALCONTENT','处理内容','VARCHAR','128','是','',9);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_RECORD_MGR','MONTHDATE','年月','VARCHAR','8','是','',10);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_RECORD_MGR','SENDFLAG','发送标识','VARCHAR','8','是','',11);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_RECORD_MGR','ISREADED','是否已读','VARCHAR','8','是','',12);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_RECORD_MGR','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_SPECIAL_RECORD_MGR','SCOPEID','范围','VARCHAR','64','否','',92);

